export enum ActionTypes {
    TASK_ADD_PENDING = 'TASK_ADD_PENDING',
    TASK_SET_SELECTED = 'TASK_SET_SELECTED',
    TASK_REMOVE_SELECTED = 'TASK_REMOVE_SELECTED',
    TASK_UPDATE_ITEM = 'TASK_UPDATE_ITEM',
    TASK_DELETE_ITEM = 'TASK_DELETE_ITEM',
    TASK_COMPLETE_ACTIVE = 'TASK_COMPLETE_ACTIVE',
    TASKS_PENDING_SET_FILTER = 'TASKS_PENDING_SET_FILTER',
    TASKS_COMPLETED_SET_FILTER = 'TASKS_COMPLETED_SET_FILTER',
    TASK_REORDER_LIST = 'TASK_REORDER_LIST',
}
