export enum ActionTypes {
    TASK_ADD_NEW = 'TASK_ADD_NEW',
    TASK_SET_SELECTED = 'TASK_SET_SELECTED',
    TASK_REMOVE_SELECTED = 'TASK_REMOVE_SELECTED',
    TASK_UPDATE_ITEM = 'TASK_UPDATE_ITEM',
    TASK_DELETE_ITEM = 'TASK_DELETE_ITEM'
}
